spring.application.name=java-devcamp
server.port=3000
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.ignore-migration-patterns=*:missing
spring.jpa.hibernate.ddl-auto=validate
management.endpoints.web.exposure.include=health,info,metrics
management.endpoints.web.base-path=
management.endpoint.health.show-details=always
management.health.rabbit.enabled=false
management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.description=Java DevCamp Product Shop
info.app.version=@project.version@
info.app.java-version=@java.version@
info.app.organization=Entelect
info.app.team=Java DevCamp
info.build.group=@project.groupId@
info.build.artifact=@project.artifactId@
info.api.base-path=/api/v1
info.api.documentation=/swagger-ui.html
info.database.type=PostgreSQL
info.database.schema.products=public
info.database.schema.customers=cis
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
